import type { Metadata } from 'next';
// import { Inter } from 'next/font/google'
import './globals.css';
import { NavbarComponent } from '@/components/Navbar/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='bg-gradient-to-r from-gray-800 to-black text-white'>
        <NavbarComponent />
        <div className='max-w-[1600px] m-auto'>{children}</div>
      </body>
    </html>
  );
}
